### ISSUE TITLE
Custom view name not being applied

### ISSUE THREAD

**Issue by sdejesusF** [DataDog/dd-sdk-android#645]
**Describe what happened**

After updating sdk version from 1.8.0 to 1.9.1 custom view names are not being used. For example: in get GetViewName of the componentpredicate I return something like "Main/Home" but in the dashboard now I see like HomeActivity.

We are using ActivityViewTrackingStrategy with ComponentPredicate

Not sure if something change that I'm not seeing in the docs that Id need to change to being able to now use custom names for views.

**Comment by sdejesusF** [comment]
Just noticed that in the json attributes I can see the custom name I gave it:
`
initial_view {	
    id 53debea2-4c94-4cf2-9773-ee113fed0d41
    name Settings/SelectSite
    url_path crc645457af758ee0fa21/SettingsSelectSiteActivity
    url_path_group crc645457af758ee0fa21/SettingsSelectSiteActivity
}
`

but Its displayed like this:

![Screen Shot 2021-06-25 at 15 47 59](https://user-images.githubusercontent.com/10758298/123442422-c62fd400-d5cc-11eb-96d5-d4512fc5de25.png)

An example using 1.8.0:

JSON value:

`initial_view {	
    id e49a650d-5c10-44d7-916f-c0e3adfe9d61
    name Settings/SelectSite
    url_path Settings/SelectSite
    url_path_group Settings/SelectSite
}`

Result in dashboard:

![Screen Shot 2021-06-25 at 15 49 08](https://user-images.githubusercontent.com/10758298/123442720-1444d780-d5cd-11eb-988f-daa4dd1f8d9b.png)


Is there anyway to override the other values as well?

**Comment by xgouchet** [comment]
Hi @sdejesusF , thanks a lot for reporting this issue. We'll take a look on this and will make sure to understand why this happen, and fix it promptly.

**Comment by sdejesusF** [comment]
thanks @xgouchet please, let me know if there is anything else I could share from my side to help you.

**Comment by 0xnm** [comment]
Hello @sdejesusF. I'm not able to reproduce it, so we need some additional info from you: does it happen only for `View Load` events you see or other events (like taps) are also affected by the target screen name difference? Can you please open a ticket using methods described here https://www.datadoghq.com/support/? By doing that we will be able to know which org these events belongs to and will be able to better investigate the issue.

**Comment by 0xnm** [comment]
Hello @sdejesusF. We've released new version [1.10.0-beta1](https://search.maven.org/artifact/com.datadoghq/dd-sdk-android/1.10.0-beta1/aar). Can you please check it and see if it resolves the issue you have?

**Comment by sdejesusF** [comment]
Hi @0xnm sorry about the delay.

I tried with 1.10.0-beta1 just now but still have the same issue :(

**Comment by 0xnm** [comment]
@sdejesusF We would need to check events received, so please open a ticket via official support channel, so that we can follow-up with more details.

**Comment by 0xnm** [comment]
Hello @sdejesusF. We didn't hear from you back on our official support channels, so I'm closing this ticket due to inactivity. Feel free to share more info if the issue still occurs.

**Comment by sdejesusF** [comment]
@0xnm sorry about that delay but since the current version was working without problems priority changed. Recently I had to update also dd iOS lib to version 1.6.0 and noticed that this is happening now on iOS as well. Not sure what could be the reason but will open a ticket. Thank you.
